import { z } from "zod";

/**
 * ============================================================================
 * INPUT CONTRACT — what the client (Product UI) sends to POST /api/robopilot
 * ============================================================================
 */
export const RequirementInputSchema = z.object({
  projectName: z.string().min(3).max(120),
  requirements: z.array(z.string().min(3).max(500)).min(1).max(20),
  constraints: z.array(z.string().min(3).max(500)).max(20).default([]),
  budgetUsd: z.number().positive().max(100_000).optional(),
  targetPlatform: z.enum(["arduino", "esp32", "unspecified"]).default("unspecified"),
  priceRegion: z.enum(["egypt", "international"]).default("egypt"),
});
export type RequirementInput = z.infer<typeof RequirementInputSchema>;

/**
 * ============================================================================
 * AI-DECOMPOSITION CONTRACT — the ONLY thing the language model is allowed to
 * produce. Pricing, compatibility, milestones and risk are computed
 * deterministically afterwards (see tools.ts) — never generated by the model.
 * ============================================================================
 */
export const ArchitectureBlockSchema = z.object({
  name: z.string(),
  purpose: z.string(),
  inputs: z.array(z.string()),
  outputs: z.array(z.string()),
});
export type ArchitectureBlock = z.infer<typeof ArchitectureBlockSchema>;

export const ProposedComponentSchema = z.object({
  role: z.string(),
  candidateName: z.string(),
  quantity: z.number().int().positive(),
  justification: z.string(),
});
export type ProposedComponent = z.infer<typeof ProposedComponentSchema>;

export const AssumptionSchema = z.object({
  statement: z.string(),
  reason: z.string(),
});
export type Assumption = z.infer<typeof AssumptionSchema>;

export const AIDecompositionSchema = z.object({
  architecture_blocks: z.array(ArchitectureBlockSchema).min(1).max(10),
  proposed_components: z.array(ProposedComponentSchema).min(1).max(15),
  assumptions: z.array(AssumptionSchema).max(10),
});
export type AIDecomposition = z.infer<typeof AIDecompositionSchema>;

/**
 * ============================================================================
 * DETERMINISTIC TOOL OUTPUT CONTRACTS
 * ============================================================================
 */
export const ComponentLineSchema = z.object({
  role: z.string(),
  name: z.string(),
  quantity: z.number().int().positive(),
  unitPriceUsd: z.number().nonnegative(),
  totalPriceUsd: z.number().nonnegative(),
  datasheetUrl: z.string(),
  status: z.enum(["approved", "not_in_catalog"]),
  priceSource: z.enum(["catalog", "live", "unavailable"]).default("catalog"),
  liveStoreName: z.string().optional(),
  liveListingUrl: z.string().optional(),
  approxLocalPrice: z.number().nonnegative().optional(),
  approxLocalCurrency: z.enum(["EGP"]).optional(),
});
export type ComponentLine = z.infer<typeof ComponentLineSchema>;

export const CompatibilityCheckSchema = z.object({
  componentA: z.string(),
  componentB: z.string(),
  interface: z.string(),
  compatible: z.boolean(),
  reason: z.string(),
});
export type CompatibilityCheck = z.infer<typeof CompatibilityCheckSchema>;

export const MilestoneSchema = z.object({
  name: z.string(),
  description: z.string(),
  dependsOn: z.array(z.string()),
  estimatedDays: z.number().positive(),
});
export type Milestone = z.infer<typeof MilestoneSchema>;

export const RiskSchema = z.object({
  category: z.enum(["schedule", "technical", "budget", "component_availability"]),
  description: z.string(),
  likelihood: z.enum(["low", "medium", "high"]),
  impact: z.enum(["low", "medium", "high"]),
  score: z.number().min(1).max(9),
  mitigation: z.string(),
});
export type Risk = z.infer<typeof RiskSchema>;

export const TestPlanItemSchema = z.object({
  target: z.string(),
  description: z.string(),
  expectedResult: z.string(),
});
export type TestPlanItem = z.infer<typeof TestPlanItemSchema>;

/**
 * ============================================================================
 * FINAL RESPONSE CONTRACT — returned by POST /api/robopilot
 * ============================================================================
 */
export const RoboPilotPlanSchema = z.object({
  requirements: z.array(z.string()),
  constraints: z.array(z.string()),
  architecture_blocks: z.array(ArchitectureBlockSchema),
  components: z.array(ComponentLineSchema),
  compatibility_checks: z.array(CompatibilityCheckSchema),
  bom_items: z.array(ComponentLineSchema),
  bom_total_usd: z.number().nonnegative(),
  milestones: z.array(MilestoneSchema),
  risks: z.array(RiskSchema),
  tests: z.array(TestPlanItemSchema),
  assumptions: z.array(AssumptionSchema),
  meta: z.object({
    provider_used: z.enum(["groq", "gemini", "stub"]),
    generated_at: z.string(),
    priceRegion: z.enum(["egypt", "international"]),
    warnings: z.array(z.string()),
  }),
});
export type RoboPilotPlan = z.infer<typeof RoboPilotPlanSchema>;
